### ISSUE TITLE
Circular saw

### ISSUE THREAD

**Issue by Ezhh** [Ezhh/RC_Issues#19]
In creative mode the full nodes placed in the saw should not get used up.

**Comment by aleokdev** [comment]
https://github.com/Sokomine/circularsaw/blob/37571e37c55e7d0c0d01ac72fb6f445c3a958dc5/init.lua#L55
circularsaw.cost_in_microblocks should be replaced all with "0" when gamemode is creative

**Comment by Ezhh** [comment]
Ohhh - hi Alex!

Thanks for doing the digging for me. :)

**Comment by aleokdev** [comment]
no problem :D
i can't try if it works since my graphic card is giving problems, sorry. Here, i made a fork with the edit, maybe you can test it: https://github.com/alexdevteam/circularsaw

**Comment by Ezhh** [comment]
I use a separate version of the mod so will need to apply the changes to that instead, but this will let me know what to look for, so is a pretty big help.

**Comment by Ezhh** [comment]
Changes on the server and will be live after next restart.
