### ISSUE TITLE
Circular saw replace bug

### ISSUE THREAD

**Issue by aleokdev** [Ezhh/RC_Issues#21]
When you place a block that is cuttable into the circular saw, grab it again and try to replace it with another item, the second item gets destroyed. I'm not sure if this is important or not since RC is creative and losing nodes is not that big of a deal, however, I'm not sure if the circular saw is also present in DL. Also,when reproducing the bug, i somehow ended with an unknown item as well. Again, not that big of a deal, just wanted to share it if the circular saw is used in any survival applications.

**Comment by Ezhh** [comment]
Not used on DL. I'm aware the unknowns can appear, but don't really see it as worth fixing.
